Create head
AnnaFesik/Landing-Page-First pull request #3
Opened 2020-07-12 15:10 UTC by AnnaFesik

Я создала основу для шапки сайта
Скачала и добавила  в папку проекта шрифт, но не поняла как его подтянуть 
Бэкграунды для блоков сделала пока цветным, чтоб мне было наглядно

2020-07-12 15:41 UTC, EgorKorol requested changes
Итого в этом PR:

1. разберись с шрифтами, подключи нужные форматы и необходимые начертания
2. приведи код к единообразному форматированию
3. исправь комментарии :)

2020-07-12 15:41 UTC, EgorKorol commented on index.html
> +    <link rel="stylesheet" href="./fonts/Rubik-Regular.ttf">
Вот видео по подключению шрифтов
https://youtu.be/GwA0BN5RgB0

2020-07-12 15:41 UTC, EgorKorol commented on index.html
> +    <link rel="stylesheet" href="./fonts/Rubik-Regular.ttf">
Тебе вроде не все начертания нужны для проекта. Проверь по макету и лишние убери.

2020-07-12 15:41 UTC, EgorKorol commented on index.html
> +                <li>Help</li>
Пункты это ссылки для перехода на другие страницы. В нашем случае оставь просто `href="#"` вместо url

2020-07-12 15:41 UTC, EgorKorol commented on index.html
> +    </div>
Логотип обычно тоже в виде ссылки, но тут можно оставить и так

2020-07-12 15:41 UTC, EgorKorol commented on index.html
> +        <img src="./img/Logo.png" alt="LaslessVPN">
LaslessVPN logo
А то не понятно что за LaslessVPN. Этот текст же будет читаться вместо изображения

2020-07-12 15:41 UTC, EgorKorol commented on index.html
> +            <button type="submit">Sign Up</button>
`type` у `button` не `submit` тут, а `button`. `type="submit"` используется для отправки форм

2020-07-12 15:41 UTC, EgorKorol commented on style.css
> +    flex-direction: row;
`row` - значение по умолчанию, не нужно его писать специально

2020-07-12 15:41 UTC, EgorKorol commented on style.css
> +    height: 120px;
Задавать жесткую высоту не лучшее решение, так как при переполнении контента (была одна строка, а при уменьшении экрана перескочило на вторую) такой способ сломает верстку, тут лучше использовать либо `min-height`, либо `padding`

2020-07-12 15:41 UTC, EgorKorol commented on style.css
> +
Разберись пожалуйста с форматированием и приведи код к одному виду :)

2020-07-12 15:41 UTC, EgorKorol commented on style.css
> +height: 36.23px;
Лучше все таки не использовать такие точные значения, можно спокойно округлить до 36px

2020-07-12 15:41 UTC, EgorKorol commented on style.css
> +flex-basis: auto;
`auto` - значение по умолчанию, не нужно его писать специально

2020-07-12 15:41 UTC, EgorKorol commented on style.css
> +flex-basis: auto;
`auto` - значение по умолчанию, не нужно его писать специально

2020-07-13 16:36 UTC, AnnaFesik commented on index.html
> +    <link rel="stylesheet" href="./fonts/Rubik-Regular.ttf">
Исправила.

2020-07-13 16:51 UTC, AnnaFesik commented on index.html
> +                <li>Help</li>
+

2020-07-13 16:56 UTC, AnnaFesik commented on index.html
> +        <img src="./img/Logo.png" alt="LaslessVPN">
+

2020-07-13 16:57 UTC, AnnaFesik commented on index.html
> +    </div>
сделала ссылкой

2020-07-13 17:02 UTC, AnnaFesik commented on index.html
> +            <button type="submit">Sign Up</button>
Поправила. Думала, что здесь должна форма отправляться, если это кнопка для входа

2020-07-13 17:05 UTC, AnnaFesik commented on style.css
> +    height: 120px;
+

2020-07-13 17:05 UTC, AnnaFesik commented on style.css
> +height: 36.23px;
+

2020-07-13 17:08 UTC, AnnaFesik commented on style.css
> +flex-basis: auto;
+

2020-07-13 17:08 UTC, AnnaFesik commented on style.css
> +flex-basis: auto;
+

2020-07-20 12:33 UTC, EgorKorol requested changes
Форматирование не исправлено осталось

2020-07-20 12:33 UTC, EgorKorol commented on index.html
> +        </div>
Тут тебе обертка `<div class="logo">` не нужна

2020-07-20 12:33 UTC, EgorKorol commented on index.html
> +        <div class="nav">
Обертка `<div class="nav">` тоже незачем

2020-07-20 12:33 UTC, EgorKorol commented on style.css
> +    font-family: 'Rubik';
Нужно еще указать запасной шрифт и семейство шрифтов. `font-family: 'Rubik', 'Arial', sans-serif;`

2020-07-20 12:33 UTC, EgorKorol commented on style.css
> +    flex-direction: row;
Не исправлено

2020-07-21 07:46 UTC, EgorKorol approved these changes

2020-07-21 07:46 UTC, merged